default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  port: 5433
  host: 127.0.0.1


development:
  <<: *default
  database: status_page_api_development

test:
  <<: *default
  database: status_page_api_test

production:
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  variables:
    timezone: "Etc/UTC"
